CREATE DATABASE SYSGAMEDB
GO

USE SYSGAMEDB
GO

CREATE TABLE AMIGO (
	AMIGOID UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	NOME NVARCHAR(150) NOT NULL
)
GO

CREATE TABLE JOGO (
	JOGOID UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	NOME NVARCHAR(150) NOT NULL,
	EMPRESTADO BIT NOT NULL,
	PROPRIETARIOID UNIQUEIDENTIFIER NOT NULL,
	AMIGOID UNIQUEIDENTIFIER
)
GO

ALTER TABLE JOGO
ADD CONSTRAINT FK_JOGO_AMIGO FOREIGN KEY(AMIGOID)
REFERENCES AMIGO (AMIGOID)
GO

